"""empty message

Revision ID: 36c8dbe8f2a7
Revises: 3b15fbf2a1ec
Create Date: 2023-09-26 21:49:12.718878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36c8dbe8f2a7'
down_revision = '3b15fbf2a1ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_dish')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_dish',
    sa.Column('order_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('dish_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['dishes.id'], name='order_dish_ibfk_1'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_dish_ibfk_2'),
    sa.PrimaryKeyConstraint('order_id', 'dish_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
